[package]
name = "kernel"
version = "0.0.1"
authors = ["Qin-Shihuang <0.0@owo.li>", "FyVoid <mythstudiofyvoid@outlook.com>"]
edition = "2021"

[dependencies]

[build-dependencies]
preprocessor = { version = "0.1.0", path = "../tools/preprocessor" }
