[build]
target = "mipsel-unknown-none"

[target.mipsel-unknown-none]
runner = "qemu-system-mipsel"
rustflags = [
    "-C", "link-arg=-Tsrc/kernel.ld",
    "-C", "force-frame-pointers=yes",
]

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]