[build]
target = "mipsel-unknown-none"

[target.mipsel-unknown-none]
# qemu-system-mipsel -cpu 4Kc -m 64 -nographic -M malta -no-reboot -kernel 
runner = "qemu-system-mipsel -cpu 4Kc -m 64 -nographic -M malta -no-reboot -kernel"
rustflags = [
    "-C", "link-arg=-Tsrc/kernel.ld",
    "-C", "force-frame-pointers=yes",
]

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]

[profile.dev]
opt-level = 0
debug = true

[profile.release]
opt-level = 1
debug = false