name: Update Main Repository Submodule Reference

on:
  push:
    branches:
      - main

jobs:
  update-submodule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: 'MOS-Rust/mos'
          token: ${{ secrets.PAT }} 
          ref: 'main'
          submodules: 'recursive'
      - name: Set up git
        run: |
          git config --global user.email "automation@svc.moe"
          git config --global user.name "MOS Automation"
      - name: Update submodule
        run: |
          git submodule update  --init --recursive --remote -f
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
      - name: Commit changes
        run: |
          git add kernel
          git commit -m "Github: Update submodule to latest commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}