name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        path: "kernel"
    - name: Checkout MOS-Rust/tools
      uses: actions/checkout@v4
      with:
        repository: "MOS-Rust/tools"
        path: "tools"
        token: ${{ secrets.PAT }} 
    - name: Checkout MOS-Rust/allocator
      uses: actions/checkout@v4
      with:
        repository: "MOS-Rust/allocator"
        path: "allocator"
        token: ${{ secrets.PAT }}
    - uses: dtolnay/rust-toolchain@nightly
    - run: rustup component add llvm-tools rust-src clippy
    - name: Build
      run: |
        cd kernel &&
        cargo +nightly build --verbose
